### ISSUE TITLE
switch to LGPL or GPL+ClassPathException?

### ISSUE THREAD

**Issue by karolherbst** [jedwards1211/Jhrome#1]
Hi,
I found your project and it seems to be a good JTabbedPane replacement with more features. I would use it, but because I want to use it in propritary software I can't.

It would be nice to hear something from your because of this.

**Comment by karolherbst** [comment]
a GNU classpath exception would be good, too: http://www.gnu.org/software/classpath/license.html

**Comment by jedwards1211** [comment]
Glad you're interested, Karol, I don't think switching to the LGPL would be a big problem. I'll read up on it tonight.

Also, I've been wondering lately if it would be possible to make the Chrome-style tabs work entirely through TabbedPaneUI.  That would be a huge change, but probably convenient for developers like you?

mit freundlichen Gruessen,
Andy

**Comment by karolherbst** [comment]
Currently I am trying out some ways implementing dynamic tabs. Things have to be discussed further. I hadn't tried out how well this will work in our environment here (we have custom look and feels and other stuff). But I think I will have an answer end of this week. I wasn't sure if you will answer at all, that's why I created this issue that early.

But for me this is the best implementation I found the last two days.

**Comment by jedwards1211** [comment]
Great, thank you!  I haven't been actively maintaining the library but I
have been good about responding to support emails.  When I'm done with work
I'll try to change the license.

**Comment by jedwards1211** [comment]
Oh, you know what?  I had forgotten, but Jhrome is released with the LGPL, so you can go ahead and use it.  I accidentally said "added GPL info" in one of my commit comments, that must have confused everyone.

**Comment by karolherbst** [comment]
Is it allowed to distribute a LGPLd jar file within propritary code? I am not sure with this, but I think it is.

**Comment by karolherbst** [comment]
The main reason to choice this component would be the advataged functionality compared to JTabbedPane. Adding a close button or even a add new Tab button is not easy doing there.

Of course we want to use a custom LookAndFeel, so there has to be a functionality to use only the "features" of Jhrome without the style.

Currently I am just testing how well this will integrate in our application.

**Comment by jedwards1211** [comment]
The idea of LGPL is that users of your program could modify Jhrome and run your program with the modified code, even though they can't modify your proprietary code.  So as long as you distribute Jhrome as a separate jar and the users can easily replace it, I see no problem.

It's definitely possible to modify the appearance of tabs arbitrarily.  The easiest way to do that would be to create a class CustomTabUI extending DefaultTabUI, and at the start of your program, do:

UIManager.getDefaults( ).put( DefaultTabUI.class.getName( ) , CustomTabUI.class.getName( ) );

**Comment by karolherbst** [comment]
I see. I will put all changes made for testing purposes on this branch: https://github.com/karolherbst/Jhrome/commit/changes

I don't know what will happen if we are deciding to choose jhrome. Maybe we will do many changes within your code (and create maybe pull request if it makes sense) or we will just use it at it is...
